// Keeps the admin panels' dictionaries (src/utils/i18n/admin1-7.js, about 540 KB) out of the public site's first download.
//
// The admin dictionaries load with the admin panels. A few of their strings are also used by the public site (the clock strip,
// the Team page, the Gallery page ...), so this script finds them and writes just those into
// src/utils/i18n/adminPublic.generated.js, which stays in the main bundle.
//
// A string counts as "used by the public site" when its key appears in any file the public site can reach: everything imported from
// src/index.js, except the two admin pages (AdminPage, SuperAdminPage), which are loaded on demand. `npm start` and `npm run build`
// run this first, so a new use of an admin string by a public page is picked up on the next start or build.
const fs = require('fs');
const path = require('path');

const src = path.join(__dirname, '..', 'src');
const i18nDir = path.join(src, 'utils', 'i18n');
const LANGS = ['en', 'ne', 'hi', 'zh', 'ta'];
const ADMIN_PAGES = new Set(['pages/AdminPage.jsx', 'pages/SuperAdminPage.jsx'].map((p) => path.join(src, p)));

const loadDictionary = (file) => {
  const text = fs.readFileSync(file, 'utf8').replace(/^\s*export default/m, 'module.exports =');
  const m = { exports: {} };
  new Function('module', 'exports', text)(m, m.exports);
  return m.exports;
};

const admin = [1, 2, 3, 4, 5, 6, 7].map((n) => loadDictionary(path.join(i18nDir, `admin${n}.js`)));
const adminKeys = new Set();
admin.forEach((d) => LANGS.forEach((l) => Object.keys(d[l] || {}).forEach((k) => adminKeys.add(k))));

// ---- files the public site can reach ----
const EXT = ['', '.js', '.jsx', '.json', '/index.js', '/index.jsx'];
const resolve = (from, spec) => {
  if (!spec.startsWith('.')) return null;
  const base = path.resolve(path.dirname(from), spec);
  for (const e of EXT) { const p = base + e; if (fs.existsSync(p) && fs.statSync(p).isFile()) return p; }
  return null;
};
const specs = (text) => [...text.matchAll(/(?:\bfrom\s*|\bimport\s*\(\s*|\brequire\s*\(\s*|\bimport\s+)['"]([^'"]+)['"]/g)].map((m) => m[1]);
const seen = new Set();
const queue = [path.join(src, 'index.js')];
while (queue.length) {
  const file = queue.pop();
  if (seen.has(file)) continue;
  seen.add(file);
  if (!/\.(jsx?)$/.test(file)) continue;
  for (const spec of specs(fs.readFileSync(file, 'utf8'))) {
    const target = resolve(file, spec);
    if (target && !ADMIN_PAGES.has(target) && !seen.has(target)) queue.push(target);
  }
}

const used = new Set();
for (const file of seen) {
  if (file.startsWith(i18nDir) || file.endsWith(`${path.sep}translations.js`)) continue;
  for (const token of fs.readFileSync(file, 'utf8').match(/[A-Za-z_][A-Za-z0-9_]*/g) || []) if (adminKeys.has(token)) used.add(token);
}

// a key built at run time ("a1_" + name) cannot be found by looking for it: refuse to guess
const dynamic = [];
for (const file of seen) {
  if (file.startsWith(i18nDir)) continue;
  const text = fs.readFileSync(file, 'utf8');
  if (/\b(?:a[1-6]|k7)_(?:\$\{|['"`]\s*\+)/.test(text)) dynamic.push(path.relative(src, file));
}
if (dynamic.length) {
  console.error('split-i18n: these public files build admin dictionary keys at run time, which cannot be split safely:\n  ' + dynamic.join('\n  '));
  process.exit(1);
}

const subset = {};
LANGS.forEach((l) => {
  subset[l] = {};
  admin.forEach((d) => Object.keys(d[l] || {}).forEach((k) => { if (used.has(k)) subset[l][k] = d[l][k]; }));
});

const out = `// Generated by scripts/split-i18n.cjs (npm start and npm run build run it first). Do not edit by hand.
// The admin-dictionary strings that the public site's own code uses. The rest of the admin dictionaries load with the admin panels
// (utils/i18n/adminAll.js).
const adminPublic = ${JSON.stringify(subset, null, 1)};

export default adminPublic;
`;
const target = path.join(i18nDir, 'adminPublic.generated.js');
if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== out) fs.writeFileSync(target, out, 'utf8');
console.log(`split-i18n: ${used.size} of ${adminKeys.size} admin strings are used by the public site (${seen.size} files scanned)`);
